version: '2'
services:
  storage:
    image: meridor/perspective-storage:${VERSION}
    volumes:
      - /var/log/perspective-storage.log:/var/log/perspective/perspective-storage.log
  rest:
    image: meridor/perspective-rest:${VERSION}
    ports:
     - "8080:8080"    
    volumes:
      - /var/log/perspective-rest.log:/var/log/perspective/perspective-rest.log
    links:
      - storage
    environment:
      - MISC_PROPERTIES=-Dperspective.storage.hosts=storage:5801
  openstack:
    image: meridor/perspective-openstack:${VERSION}
    volumes:
      - /var/log/perspective-openstack.log:/var/log/perspective/perspective-openstack.log
    links:
      - storage
    environment:
      - MISC_PROPERTIES=-Dperspective.storage.hosts=storage:5801
    depends_on:
      - rest
  docker:
    image: meridor/perspective-docker:${VERSION}
    volumes:
      - /var/log/perspective-docker.log:/var/log/perspective/perspective-docker.log
    links:
      - storage
    environment:
      - MISC_PROPERTIES=-Dperspective.storage.hosts=storage:5801
    depends_on:
      - rest